### ISSUE TITLE
Cannot connect with Composer on mac

### ISSUE THREAD

**Issue by VessoVit** [szymonkaliski/EEG2OSC#1]
Hi @szymonkaliski , 
I am trying to run EEG2OSC on Mac and connect it to XavierComposer, however the application breaks with the following error: 
Assertion failed: (sizeof(emoState_t) == emoStateBytes.size()), function serialize, file ../../include/EmoEventLib/EmoEvent.h, line 306.

It does connect with EmoComposer 1.0.6, however I cannot obtain any data. EmoEngine is logging "Reply with error code 774". 

Can you provide more info on what were the active versions for which you build ?

**Comment by VessoVit** [comment]
It does work fine with 2.0.0.20

**Comment by szymonkaliski** [comment]
> It does work fine with 2.0.0.20

Yes, that's what I was using! :)
